name: doxygen

on:
  push:
    branches:
      - main
      
jobs:
  generate-and-push-documentation:
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        shell: bash
        
      - name: Generate Doxygen Documentation
        run: doxygen
        shell: bash
        
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update documentation         
